services:
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - index_data:/chroma/.chroma/index
    ports:
      - 8000:8000
    networks:
      - net
  postgres:
    hostname: 127.0.0.1
    image: pgvector/pgvector:pg16
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=ChangeMe
    volumes:
      - postgres_data:/var/lib/postgresql/data
    #   - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  index_data:
    driver: local
  postgres_data:
    driver: local
  backups:
    driver: local

networks:
  net:
    driver: bridge