services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: streamlit run src/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - 8501:8501
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
      - CHROMA_HOST=host.docker.internal
      - CHROMA_PORT=9000
      - DB_URL=postgresql://myuser:ChangeMe@postgres:5432/api
    links:
      - postgres
    volumes:
      - .:/app
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - index_data:/chroma/.chroma/index
    ports:
      - 9000:8000
    networks:
      - net
  postgres:
    hostname: 127.0.0.1
    image: pgvector/pgvector:pg16
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=ChangeMe
    volumes:
      - postgres_data:/var/lib/postgresql/data
  ollama:
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    volumes:
      - ollama:/root/.ollama
      - ./etc/ollama_entrypoint.sh:/entrypoint.sh
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    ports:
      - 11434:11434
    entrypoint: ['/usr/bin/bash', '/entrypoint.sh']
    environment:
      - OLLAMA_HOST=0.0.0.0
    profiles: ['cpu']
  open_webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open_webui
    volumes:
      - open_webui:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://host.docker.internal:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
volumes:
  index_data:
    driver: local
  postgres_data:
    driver: local
  backups:
    driver: local
  ollama: {}
  open_webui: {}

networks:
  net:
    driver: bridge
